 export const baraja = [
    {palo: 'oro', valor: 1, img:"fotos/1oro.png"},
    {palo: 'oro', valor: 2,img:"fotos/2oro.png"},
    {palo: 'oro', valor: 3,img:"fotos/3oro.png"},
    {palo: 'oro', valor: 4,img:"fotos/4oro.png"},
    {palo: 'oro', valor: 5,img:"fotos/5oro.png"},
    {palo: 'oro', valor: 6,img:"fotos/6oro.png"},
    {palo: 'oro', valor: 7,img:"fotos/7oro.png"},
    {palo: 'oro', valor: 'J',img:"fotos/10oro.png"},
    {palo: 'oro', valor: 'Q',img:"fotos/11oro.png"},
    {palo: 'oro', valor: 'K',img:"fotos/12oro.png"},
    {palo: 'copas', valor: 1,img:"fotos/1copas.png"},
    {palo: 'copas', valor: 2,img:"fotos/2copas.png"},
    {palo: 'copas', valor: 3,img:"fotos/3copas.png"},
    {palo: 'copas', valor: 4,img:"fotos/4copas.png"},
    {palo: 'copas', valor: 5,img:"fotos/5copas.png"},
    {palo: 'copas', valor: 6,img:"fotos/6copas.png"},
    {palo: 'copas', valor: 7,img:"fotos/7copas.png"},
    {palo: 'copas', valor: 'J',img:"fotos/10copas.png"},
    {palo: 'copas', valor: 'Q',img:"fotos/11copas.png"},
    {palo: 'copas', valor: 'K',img:"fotos/12copas.png"},
    {palo: 'espadas', valor: 1,img:"fotos/1espadas.png"},
    {palo: 'espadas', valor: 2,img:"fotos/2espadas.png"},
    {palo: 'espadas', valor: 3,img:"fotos/3espadas.png"},
    {palo: 'espadas', valor: 4,img:"fotos/4espadas.png"},
    {palo: 'espadas', valor: 5,img:"fotos/5espadas.png"},
    {palo: 'espadas', valor: 6,img:"fotos/6espadas.png"},
    {palo: 'espadas', valor: 7,img:"fotos/7espadas.png"},
    {palo: 'espadas', valor: 'J',img:"fotos/10espadas.png"},
    {palo: 'espadas', valor: 'Q',img:"fotos/11espadas.png"},
    {palo: 'espadas', valor: 'K',img:"fotos/12espadas.png"},
    {palo: 'bastos', valor: 1,img:"fotos/1bastos.png"},
    {palo: 'bastos', valor: 2,img:"fotos/2bastos.png"},
    {palo: 'bastos', valor: 3,img:"fotos/3bastos.png"},
    {palo: 'bastos', valor: 4,img:"fotos/4bastos.png"},
    {palo: 'bastos', valor: 5,img:"fotos/5bastos.png"},
    {palo: 'bastos', valor: 6,img:"fotos/6bastos.png"},
    {palo: 'bastos', valor: 7,img:"fotos/7bastos.png"},
    {palo: 'bastos', valor: 'J',img:"fotos/10bastos.png"},
    {palo: 'bastos', valor: 'Q',img:"fotos/11bastos.png"},
    {palo: 'bastos', valor: 'K',img:"fotos/12bastos.png"},
  ];

  